### PR TITLE
Disable Zoom to Selected Site when no site is selected 

### LINKED ISSUE #216: [BUG] Zoom to selected site stops working in a certain scenario
**Describe the bug**
The Zoom to Selected Site button's functionality stops working as soon as you click it when no site is selected.

**To Reproduce**
* open the Dashboard (https://dashboard.datamermaid.org/)
* click Zoom to Selected Site without selecting a site before
* now select a site
* click Zoom to Selected Site - it won't zoom to it nor to any number of sites you will try from here on

**Expected behavior**
The Zoom to Selected Site button works when a site is selected in all situations.

**Additional context**
The issue here is that when you click the button without selecting a site, you set a state (`zoomToSite`) in the `MermaidDash` component that cannot be undone. And that new state will conflict with a correct use of the button afterwards when the `MermaidDash` component [checks](https://github.com/data-mermaid/mermaid-dash/blob/55797766535e3e4a803539cd3a92691b07163c71/src/components/LeafletMap.js#L190) for difference in its previous and current state in order to perform the zoom.

I'll submit a possible PR fix to this in a bit.

### PR DESCRIPTION
**Pull request by vpop**
This fixes #216.

It will also:
* avoid re-rendering the `MermaidDashboard` and `LeafletMap` components when the button is clicked
* improve on user friendliness, so we don't have a button that can be clicked and does nothing in certain situations

For this fix, I've added a couple of props to the theme to match the style of the Leaflet library's Zoom in/out buttons when `disabled`, since they are part of the same group of buttons (top-left map controls). Another options would have been to use the `notAllowed` existing property, but there are a couple of inconsistencies if using that. I can get into the details of it if you want to.

### CODE REVIEW

File: src/styles/MermaidStyledComponents.js [hunk 1]
```diff
@@ -27,7 +32,7 @@ export const ButtonStyle = styled('button')`
     '0px 1px 3px 0px rgba(0,0,0,0.2), 0px 1px 1px 0px rgba(0,0,0,0.14), 0px 2px 1px -1px rgba(0,0,0,0.12)'};
   transform: ${props => props.theme.initialTranslate};
   transition: 0.2s ease-out;
-  cursor: ${props => (props.notAllowed ? 'not-allowed' : 'pointer')};
+  cursor: ${props => (props.notAllowed ? 'not-allowed' : props.disabled ? 'default' : 'pointer')};
```
Comment (tienhoah) [inline src/styles/MermaidStyledComponents.js:35]: can you make a small change from 'default` to 'not-allowed`?

**Comment by tienhoah** [comment]
This looks good to me. Just one small change. Very appreciate your help!

File: src/styles/MermaidStyledComponents.js (hunk 1 above)
Comment (vpop) [reply src/styles/MermaidStyledComponents.js:35]: Sure. The reason behind the cursor being `default` was to match the zoom in/out buttons' behavior of disabled, since they are in the same group of map control buttons.

Comment (tienhoah) [reply src/styles/MermaidStyledComponents.js:35]: Got it! Consistency is great. I'm fine with that.

**Review by tienhoah — APPROVED** [review]

**Comment by saanobhaai** [comment]
Hello vpop and happy new year -- I just merged an earlier PR which is now causing a conflict on this one. Just need to change the location of `theme.js` -- can you resolve? Then I'll merge (promptly!).
